spring:
  application.name: link.tree
  datasource:
    url: ENC(XBUSi0SKEwyXcqcBlqZhWMTd60JExrlu3hMVmfppicokOcDbVTas6TzZJbnZshNvrZdLrliLi/GzNG8Jl2SAxTwiSsjxnT23pBNSw3NvygYzDeRX2edYeJ3ZTbMaUX6dh4lSrLiTxzH3R1qqO4YDobQzjF6Kf8wYKdR7KX19vg89AcGqZJEoo+0UJHYohUha)
    username: ENC(CqR5l09/l73ZsBLN91OL+Mp+12Kmlw+D)
    password: ENC(jTPup2V27WdgNkLX8iped/mRWB3+PwLusG+Ecqr4nqU=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  batch:
    jdbc.initialize-schema: embedded
    job:
      name: linkGenerationJob
      enabled: false

feign:
  client:
    config:
      postClient:
        connectTimeout: 5000
        readTimeout: 5000
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3

ftp:
  host: ENC(DhL0xr1dNMsqxH607y/UeUG2aDU2EK+LJdegDOMA/8knvD9mrwft78SQvHNQPy4m)
  port: 21
  username: ENC(Lbtc+LHr0n3AqyqxhMKmSCZSvWhCw20fUqQXAmh7TZIAdIiqWKeZ8w==)
  password: ENC(VXtMpPSnSMa5mKUtumDkRp18N1wKZO9WwoBJ3BjqxJpQ4EJKJDZMwg==)

jasypt:
  encryptor:
    password: ${jasyptPassword}
    algorithm: PBEWithMD5AndDES

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.hibernate.type: INFO
    org.hibernate.boot.model: INFO
    org.hibernate.query.sqm: INFO

decorator:
  datasource:
    p6spy:
      logging: slf4j
      log-format: '%(currentTime)|%(executionTime)ms|connection %(connectionId)|[%(category)]:%(sql)'
      log-filter:
        pattern: '^(?!.*(BATCH_JOB_|BATCH_STEP_)).*$'