spring:
  application.name: link.tree
  datasource:
    url: ENC(XBUSi0SKEwyXcqcBlqZhWMTd60JExrlu3hMVmfppicokOcDbVTas6TzZJbnZshNvrZdLrliLi/GzNG8Jl2SAxTwiSsjxnT23pBNSw3NvygYzDeRX2edYeJ3ZTbMaUX6dh4lSrLiTxzH3R1qqO4YDobQzjF6Kf8wYKdR7KX19vg89AcGqZJEoo+0UJHYohUha)
    username: ENC(CqR5l09/l73ZsBLN91OL+Mp+12Kmlw+D)
    password: ENC(jTPup2V27WdgNkLX8iped/mRWB3+PwLusG+Ecqr4nqU=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  batch:
    jdbc.initialize-schema: embedded
    job.name: linkGenerationJob

feign:
  client:
    config:
      postClient:
        connectTimeout: 5000
        readTimeout: 5000
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3

jasypt:
  encryptor:
    password: ${jasyptPassword}
    algorithm: PBEWithMD5AndDES

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.hibernate.type: INFO
    org.hibernate.boot.model: INFO
    org.hibernate.query.sqm: INFO