server.port: 8088

spring:
  application.name: link.tree
  datasource:
    url: ENC(XBUSi0SKEwyXcqcBlqZhWMTd60JExrlu3hMVmfppicokOcDbVTas6TzZJbnZshNvrZdLrliLi/GzNG8Jl2SAxTwiSsjxnT23pBNSw3NvygYzDeRX2edYeJ3ZTbMaUX6dh4lSrLiTxzH3R1qqO4YDobQzjF6Kf8wYKdR7KX19vg89AcGqZJEoo+0UJHYohUha)
    username: ENC(CqR5l09/l73ZsBLN91OL+Mp+12Kmlw+D)
    password: ENC(jTPup2V27WdgNkLX8iped/mRWB3+PwLusG+Ecqr4nqU=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  batch:
    jdbc.initialize-schema: embedded
    job:
      name: crawlJob
      enabled: false
  main:
    web-application-type: none

feign:
  client:
    config:
      postClient:
        connectTimeout: 5000
        readTimeout: 5000
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3

ftp:
  host: localhost
  port: 21
  username: user
  password: pass

slack:
  bot-token: ENC(y+36Ok3MGuvAHPw0LCD1fK0c1skx+oQQMkcQghAZKLxMiH6CAvCcWE1RN4dUAsUAoBMZWDByEk/cyU1QHIBO86gUrkv7rh4edXrw0Efjnfk=)
  channel: ENC(d8+EXqMeA+qsCeMnO5uqPiDG9srpQKAcRIJW7/jPfo0=)

jasypt:
  encryptor:
    password: ${jasyptPassword}
    algorithm: PBEWithMD5AndDES

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.hibernate.type: INFO
    org.hibernate.boot.model: INFO
    org.hibernate.query.sqm: INFO

decorator:
  datasource:
    p6spy:
      logging: slf4j
      log-format: '%(currentTime)|%(executionTime)ms|connection %(connectionId)|[%(category)]:%(sql)'
      log-filter:
        pattern: '^(?!.*(BATCH_JOB_|BATCH_STEP_)).*$'
