spring:
  application.name: link.stacker
  datasource:
    url: ENC(awEWgbb1L1yQ2yfsO/QMtE3phdQ6mLPtM9aeYeRyWFMY71rGwSmQHxzYNomEvGHZXFiSsu5mRoYmQno0E5yo1LG8rziGe2wbzprYFS0IwqN7Pvm5rTKKIOatVrkczBXkGBY98cSMFsY7bt688JeDSJEqCczhkmz07mV4m92zIWzYtzs6swPtZrHzUYalqMy0)
    username: ENC(CqR5l09/l73ZsBLN91OL+Mp+12Kmlw+D)
    password: ENC(jTPup2V27WdgNkLX8iped/mRWB3+PwLusG+Ecqr4nqU=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  batch:
    jdbc.initialize-schema: embedded
    job.name: simpleJob

feign:
  client:
    config:
      postClient:
        connectTimeout: 5000
        readTimeout: 5000
        retryer:
          period: 100
          maxPeriod: 1000
          maxAttempts: 3

jasypt:
  encryptor:
    password: ${jasyptPassword}
    algorithm: PBEWithMD5AndDES

logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org.hibernate.type: INFO
    org.hibernate.boot.model: INFO
    org.hibernate.query.sqm: INFO